### ISSUE TITLE
error login

### ISSUE THREAD

**Issue by Wayyu03** [ivan42118/perpustakaan#1]
login gagal padahal nama dan password sudah sesuai

**Comment by herlanyusriana** [comment]
edit phpmyadminnya di varchar password ubah ke 50 atau 32 soalnya encrypt md5 membutuhkan kata lebih dari 32

**Comment by Artaya25** [comment]
masih eror padalah udah di ganti, sama username dan password udah sesuai sama data yang di database, tetep nggak bisa login

**Comment by ghufron827** [comment]
login gagal padahal nama dan password sudah sesuai

**Comment by ivan42118** [comment]
Hallo, untuk masalah gagal login saya sudah update databasenya, silahkan download lagi databasenya ya, terima kasih.
